version: 2


jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.3
    steps:
      - checkout
      -   run:
            name: Create/update infrastructure
            command: |
              terraform init -input=false
              terraform plan -out=tfplan
              terraform apply -input=false tfplan
