version: 2

deploy_infrastructure: &deploy_infrastructure
  run:
    name: Create/update infrastructure
    command: |
      source $BASH_ENV
      terraform init -input=false
      terraform plan -out=tfplan
      terraform apply -input=false tfplan

jobs:
  deploy-ecr-repository:
    docker:
      - image: hashicorp/terraform:0.12.3
    steps:
      - checkout
      - *deploy_infrastruture
